version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: team-backend
    ports:
      - "8090:8090"
    networks:
      - team-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JASYPT_ENCRYPTOR_PASSWORD=my-secret-key

  frontend:
    build:
      context: ./frontend
    container_name: team-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - team-network

networks:
  team-network:
    driver: bridge
